function PolyRoots

    %Checking to see if there is already a gui open
    mainFig = findall(0,'Tag','ROOTS_GUI');
    if ~isempty(mainFig)
        figure(mainFig)       
        return
    end
    
    %Creating th emain figure
    handles.mainFigure = figure('Name','Polynomial Roots',...
                                'Tag','ROOTS_GUI',...
                                'NumberTitle','off',...
                                'Units','normalized',...
                                'Position',[.025 .025 .95 .95],...
                                'MenuBar','none',...
                                'CloseRequestFcn',@closeRootGUI);
%--------------------------------------------------------------------------          
    %Creating the Panels                        
    handles.Panel.Graph = uipanel('Parent',handles.mainFigure,...
                                  'Title','Graphs',...
                                  'TitlePosition','centertop',...
                                  'Tag','grpahPanel',...
                                  'Visible','on',...
                                  'FontSize',16,...
                                  'FontWeight','bold',...
                                  'BorderType','beveledout',...
                                  'BorderWidth',2,...
                                  'Position',[ .325 .05 .65 .9]);
%-------------------------------------------------------------------------- 
    handles.Control.XMin = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','edit',...
                                  'String','-50',...
                                  'Tag','xMinEdit',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .1 .05 .05 .05]);
                              
    handles.Control.XMax = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','edit',...
                                  'String','50',...
                                  'Tag','xMaxEdit',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .2 .05 .05 .05]);
                              
    handles.Control.YMin = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','edit',...
                                  'String','-50',...
                                  'Tag','yMinEdit',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .3 .05 .05 .05]);
                              
    handles.Control.YMax = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','edit',...
                                  'String','50',...
                                  'Tag','yMaxEdit',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .4 .05 .05 .05]);
                              
    handles.Control.XMinText = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','Text',...
                                  'String','XMin',...
                                  'Tag','xMinText',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .1 .01 .05 .03]);
                              
    handles.Control.XMaxText = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','Text',...
                                  'String','XMax',...
                                  'Tag','xMaxText',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .2 .01 .05 .03]);
                              
    handles.Control.YMinText = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','Text',...
                                  'String','YMin',...
                                  'Tag','yMinText',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .3 .01 .05 .03]);
                              
    handles.Control.YMaxText = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','Text',...
                                  'String','YMax',...
                                  'Tag','yMaxText',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .4 .01 .05 .03]);
                              
    handles.Control.SetLimits = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','pushbutton',...
                                  'String','Set Limits',...
                                  'Tag','limitsButton',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .5 .04 .1 .05]);
                              
    handles.Control.ResetLimits = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','pushbutton',...
                                  'String','Reset Limits',...
                                  'Tag','resetLimsButton',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .65 .04 .1 .05]);
    handles.Control.AutoLimits = uicontrol('Parent',handles.Panel.Graph,...
                                  'Style','pushbutton',...
                                  'String','Auto Limits',...
                                  'Tag','autoLimsButton',...
                                  'FontSize',14,...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .8 .04 .1 .05]);
                              
%--------------------------------------------------------------------------                              
    handles.Panel.Degree = uipanel('Parent',handles.mainFigure,...
                                  'Title','Select Degree',...
                                  'TitlePosition','centertop',...
                                  'Tag','degreePanel',...
                                  'Visible','on',...
                                  'FontSize',16,...
                                  'FontWeight','bold',...
                                  'BorderType','beveledout',...
                                  'BorderWidth',2,...
                                  'Position',[ .175 .65 .125 .3]);  
%--------------------------------------------------------------------------                          
    handles.ButtonGroup.Degree = uibuttongroup('Parent',handles.Panel.Degree,...
                                  'Tag','degreeButtonGroup',...
                                  'Visible','off',...
                                  'Position',[ .1 .25 .8 .5],...
                                  'SelectionChangedFcn',{@degreeChanged,handles});

    handles.Control.Quadratic = uicontrol('Parent',handles.ButtonGroup.Degree,...
                                  'Style','radiobutton',...
                                  'String','Quadratic',...
                                  'Tag','degreeButton',...
                                  'Enable','off',...
                                  'Units','normalized',...
                                  'Position',[ .2 .7 .8 .2],...
                                  'HandleVisibility','off');
                              
    handles.Control.Cubic = uicontrol('Parent',handles.ButtonGroup.Degree,...
                                  'Style','radiobutton',...
                                  'String','Cubic',...
                                  'Tag','degreeButton',...
                                  'Enable','off',...
                                  'Units','normalized',...
                                  'Position',[ .2 .4 .8 .2],...
                                  'HandleVisibility','off');
                              
    handles.Control.Quartic = uicontrol('Parent',handles.ButtonGroup.Degree,...
                                  'Style','radiobutton',...
                                  'String','Quartic',...
                                  'Tag','degreeButton',...
                                  'Enable','off',...
                                  'Units','normalized',...
                                  'Position',[ .2 .1 .8 .2],...
                                  'HandleVisibility','off');
                              
    handles.ButtonGroup.Degree.Visible = 'on'; 
%--------------------------------------------------------------------------           
    handles.Panel.Mode = uipanel('Parent',handles.mainFigure,...
                                  'Title','Select Mode',...
                                  'TitlePosition','centertop',...
                                  'Tag','modePanel',...
                                  'Visible','on',...
                                  'FontSize',16,...
                                  'FontWeight','bold',...
                                  'BorderType','beveledout',...
                                  'BorderWidth',2,...
                                  'Position',[ .025 .65 .125 .3]);

%--------------------------------------------------------------------------
    handles.ButtonGroup.Mode = uibuttongroup('Parent',handles.Panel.Mode,...
                                  'Tag','modeButtonGroup',...
                                  'Visible','off',...
                                  'Position',[ .1 .25 .8 .5],...
                                  'SelectionChangedFcn',{@modeChanged,handles});

    handles.Control.Approximation = uicontrol('Parent',handles.ButtonGroup.Mode,...
                                  'Style','radiobutton',...
                                  'String','Approximation',...
                                  'Tag','modeButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .2 .1 .6 .3],...
                                  'HandleVisibility','off');
                              
    handles.Control.TrueValue = uicontrol('Parent',handles.ButtonGroup.Mode,...
                                  'Style','radiobutton',...
                                  'String','True Value',...
                                  'Tag','modeButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[ .2 .6 .6 .3],...,
                                  'Value',0,...
                                  'HandleVisibility','off');
                              
    handles.ButtonGroup.Mode.Visible = 'on';   
    
%--------------------------------------------------------------------------                                  
    handles.Panel.Coefficients = uipanel('Parent',handles.mainFigure,...
                                  'Title','Enter Coefficients',...
                                  'TitlePosition','centertop',...
                                  'Tag','coefficientsPanel',...
                                  'Visible','on',...
                                  'FontSize',16,...
                                  'FontWeight','bold',...
                                  'BorderType','beveledout',...
                                  'BorderWidth',2,...
                                  'Position',[ .025 .375 .275 .25]);                           
                        
%--------------------------------------------------------------------------       
    handles.Control.Run = uicontrol('Parent', handles.Panel.Coefficients,...
                                  'Style','pushbutton',...
                                  'String','Run',...
                                  'Tag','runButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[.1/3 .025 .45 .4]);

    handles.Control.Clear = uicontrol('Parent', handles.Panel.Coefficients,...
                                  'Style','pushbutton',...
                                  'String','Clear',...
                                  'Tag','clearButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[(.45 +.2/3) .025 .45 .4]);

    handles.Control.Coefficients = uicontrol('Parent', handles.Panel.Coefficients,...
                                  'Style','edit',...
                                  'String',{},...
                                  'Tag','clearButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[.1/3 .5 1-(.2/3) .4]);
%--------------------------------------------------------------------------        
    handles.Axes.Graph = axes('Parent',handles.Panel.Graph,...
                             'Tag','graph',...
                             'Position', [ .1 .15 .8 .8],...
                             'XLim',[-50 50],...
                             'YLim',[-50 50],...
                             'XGrid','on',...
                             'YGrid','on');
                         
 %--------------------------------------------------------------------------                              
    handles.Panel.Roots = uipanel('Parent',handles.mainFigure,...
                                  'Title','Roots!',...
                                  'TitlePosition','centertop',...
                                  'Tag','rootsPanel',...
                                  'Visible','on',...
                                  'FontSize',16,...
                                  'FontWeight','bold',...
                                  'BorderType','beveledout',...
                                  'BorderWidth',2,...
                                  'Position',[ .025 .0625 .275 .25]); 
                              
%--------------------------------------------------------------------------                                   
    handles.Control.FindRoots = uicontrol('Parent', handles.Panel.Roots,...
                                  'Style','pushbutton',...
                                  'String','Set Root Ticks',...
                                  'Tag','findFootsButton',...
                                  'Enable','on',...
                                  'Units','normalized',...
                                  'Position',[.1/3 .3 1-(.2/3) .4],...
                                  'BackgroundColor',[0.4196    1.0000    0.6118]);                              
                              
%--------------------------------------------------------------------------       

    set(handles.Control.Run,'Callback',{@coefficientOptions,handles}); 
    set(handles.Control.Clear,'Callback',{@coefficientOptions,handles}); 
    set(handles.Control.SetLimits,'Callback',{@setAxesLimits,handles});
    set(handles.Control.ResetLimits,'Callback',{@setAxesLimits,handles});
    set(handles.Control.AutoLimits,'Callback',{@setAxesLimits,handles});
    set(handles.Control.FindRoots,'Callback',{@matlabRoots,handles});


    
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function closeRootGUI(src,~)
    answer = questdlg('Do you want to close the figure?','Close','Yes','No','No');
    switch answer
        case 'Yes'
            delete(src);
        case 'No'
            return;
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function coefficientOptions(src,~,handles)
    switch src.Tag
        case 'runButton'                        
            diplayGraph(handles,handles.Control.Coefficients.String);
        case 'clearButton'
            handles.Control.Coefficients.String = {};
            delete(handles.Axes.Graph.Children);
    end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function modeChanged(~,event,~)

    switch event.NewValue.String
        case 'Approximation'
            degreeButtons = findall(0,'Tag','degreeButton');
            for i = 1:length(degreeButtons)
                set(degreeButtons(i),'Enable','off');
            end
            
        case 'True Value'
            degreeButtons = findall(0,'Tag','degreeButton');
            for i = 1:length(degreeButtons)
                set(degreeButtons(i),'Enable','on');
            end
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function degreeChanged(src,~,~)
    switch src.Tag
        case 'quadButton'
        case 'cubicButton'
        case 'quartButton'
    end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function setAxesLimits(src,~,handles)

    switch src.Tag
        case 'limitsButton'
            
            limits.xMin = handles.Control.XMin.String;
            limits.xMax = handles.Control.XMax.String;
            limits.yMin = handles.Control.YMin.String;
            limits.yMax = handles.Control.YMax.String;
            
            lims = fields(limits);

            for i = 1:length(lims)
                limits.(lims{i}) = str2double(limits.(lims{i}));
                if isnan(limits.(lims{i}))
                    warndlg('One of the limits is non-numeric','Set Limits');
                    handles.Control.XMin.String = 'XMin'; 
                    handles.Control.XMax.String = 'XMax';            
                    handles.Control.YMin.String = 'YMin';
                    handles.Control.YMax.String = 'YMax';
                    return
                end

            end
            
            if limits.xMin < limits.xMax && limits.yMin<limits.yMax
                handles.Axes.Graph.XLim = [limits.xMin limits.xMax];
                handles.Axes.Graph.YLim = [limits.yMin limits.yMax];
            else
                warndlg('Check Limits. Bounds are incorrect.','Set Limits');
                handles.Control.XMin.String = 'XMin'; 
                handles.Control.XMax.String = 'XMax';            
                handles.Control.YMin.String = 'YMin';
                handles.Control.YMax.String = 'YMax';
                return
            end
        case 'resetLimsButton'
            
            handles.Control.XMin.String = '-50'; 
            handles.Control.XMax.String = '50';            
            handles.Control.YMin.String = '-50';
            handles.Control.YMax.String = '50';
            
            handles.Axes.Graph.XLim = [-50 50];
            handles.Axes.Graph.YLim = [-50 50];
        case 'autoLimsButton'
            polyLine = findall(0,'Tag','polyLine');
            
            if ~isempty(polyLine)
                handles.Control.XMin.String = num2str(min(polyLine.XData)); 
                handles.Control.XMax.String = num2str(max(polyLine.XData));            
                handles.Control.YMin.String = num2str(min(polyLine.YData));
                handles.Control.YMax.String = num2str(max(polyLine.YData));

                handles.Axes.Graph.XLim = [min(polyLine.XData) max(polyLine.XData)];
                handles.Axes.Graph.YLim = [min(polyLine.YData) max(polyLine.YData)];
            end
    end
end


function matlabRoots(~,~,handles)
  
    diplayGraph(handles,handles.Control.Coefficients.String);
    setRootTicks(handles,handles.Control.Coefficients.String);

end

